#
#   Copyright 2025 Aiven Oy and project contributors
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing,
#    software distributed under the License is distributed on an
#    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#    KIND, either express or implied.  See the License for the
#    specific language governing permissions and limitations
#    under the License.
#
#  SPDX-License-Identifier: Apache-2

# Workflow to check pull requests and new commits to main branches
# This checks the source in the state as if after the merge.
name: Deployment checks
on:
  push:
    branches:
      - 'main'

# Disallow concurrent runs for the same PR by cancelling in-progress runs
# when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # builds aiven-commons and all modules. Does not deploy.
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: maven

      - name: Build (Maven)
        run: mvn -P ci --batch-mode clean install

      - name: "Upload build failure reports"
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: unit-test-results
          path: |
            **/target/*-reports/**
          retention-days: 1

  # modules that had changes in the PR and are SNAPSHOT versions will be deployed.
  check_deployments:
    needs: [build]
    strategy:
      matrix:
        module: [ '.', 'collections', 'google-utils', 'kafka-config', 'kafka-testkit', 'strings', 'system', 'timing', 'velocity' ]

    name: Check deployments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: maven

      - name: Get changed files in the ${{ matrix.module }} folder
        id: changed-files-specific
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files: ${{ matrix.module }}/**

      - name: Extract Maven project version for ${{ matrix.module }}  ${{ steps.changed-files-specific.outputs.any_changed }}
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: echo "version=$(mvn -f ${{ matrix.module }} -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
        id: project

      - name: Setup Maven settings.xml
        uses: s4u/maven-settings-action@v4.0.0
        with:
          sonatypeSnapshots: true
          servers: |
            [{
              "id": "central",
              "username": "${{ secrets.CLAUDE_ID }}",
              "password": "${{ secrets.CLAUDE_PASSWORD }}"
            }, {
              "id": "central-snapshot",
              "username": "${{ secrets.CLAUDE_ID }}",
              "password": "${{ secrets.CLAUDE_PASSWORD }}"
            }]

      - name: Deploy (Maven ${{ inputs.module-name }} ${{ steps.project.outputs.version }})
        if: steps.changed-files-specific.outputs.any_changed == 'true' && contains(steps.project.outputs.version , '-SNAPSHOT')
        run: mvn -f ${{ matrix.module }} -P sign --batch-mode -Dgpg.signer=bc deploy
        env:
          MAVEN_GPG_KEY: ${{ secrets.GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
